
colors:
  period:
    - "#0889A6"
    - "#F1801F"
    - "#006C43"
    - "#FFD93D"
  region:
    - "#0077b6"
    - "#e07a5f"
    - "#f2cc8f"
    - "#81b29a"
  index:
    - "#C7D530"
    - "#79D6F0"
    - "#E25A53"
  total_WU: "#D1495B"
